### PR TITLE
SDK-239: Cache OWAs in the .m2 repository to avoid the need for Inter…

### PR DESCRIPTION
**Pull request by ODORA0**
…net during building and running servers

**Issue worked on:** https://issues.openmrs.org/browse/SDK-239

### CODE REVIEW

**Comment by ODORA0** [comment]
This is still a WIP

**Comment by ODORA0** [comment]
@ssmusoke please review this, I basically followed how maven handles caching in relation to how OWAs should be cached. For where Travis has a build failure, I am creating a class for `owaproject` and probably adding the methods `getArtifactID ` , `getDescription ` and  `getScm `that maven also handles at class level.

Please guide

**Comment by dkayiwa** [comment]
@ODORA0 can you start by fixing the travis build failure which is about an undeclared class `OwaProject`?

**Comment by ODORA0** [comment]
I have created the class for `OwaProject` also added the respective methods, I think creating fields for the Travis errors shown will be a work around, any thoughts @dkayiwa

**Comment by ODORA0** [comment]
hello @dkayiwa @ssmusoke I created local static variable for `OPENMRS_USERNAME` and `OPENMRS_OWA_REPO` and also fixed a couple of errors too, although for the current build failure I would like to be guided, I could import the class [Bintray.java](https://github.com/openmrs/openmrs-sdk/blob/master/maven-plugin/src/main/java/org/openmrs/maven/plugins/bintray/Bintray.java) since it contains method declarations for the failing methods, or maybe create them within `BuildDistro.java`

**Comment by ODORA0** [comment]
Any reviews on this so far

**Comment by ssmusoke** [comment]
Changes implemented by https://github.com/openmrs/openmrs-sdk/pull/181

**Pull request closed without merging**
