### PR TITLE
SDK-317: Mitigating Module not found error when building the frontend

### PR DESCRIPTION
**Pull request by wikumChamith**
Add legacy-peer-deps argument to npm commands.

jira ticket: https://issues.openmrs.org/browse/SDK-317

### CODE REVIEW

**Comment by dkayiwa** [comment]
Should we run `--legacy-peer-deps` all the time? Or should it be optional?

**Comment by wikumChamith** [comment]
> Should we run `--legacy-peer-deps` all the time? Or should it be optional?

We could make it optional but I noticed we are already using this here: https://github.com/openmrs/openmrs-distro-referenceapplication/blob/ba72803c0e5cf39a45d26fcc05801164a0781347/frontend/Dockerfile#L12-L13

**Comment by dkayiwa** [comment]
By the way, what does that option do? 😊

**Comment by dkayiwa** [comment]
By the way, can we also replace `spaCoreVersion` with `appShellVersion`?

**Comment by wikumChamith** [comment]
> By the way, can we also replace `spaCoreVersion` with `appShellVersion`?

In this PR or in a different PR?

**Comment by dkayiwa** [comment]
> In this PR or in a different PR?

In a different PR. You do not need to create a ticket for it.

**Comment by wikumChamith** [comment]
> > In this PR or in a different PR?
> 
> In a different PR. You do not need to create a ticket for it.

@dkayiwa I created the PR: https://github.com/openmrs/openmrs-sdk/pull/237

**Comment by wikumChamith** [comment]
@dkayiwa I made using  --legacy-peer-deps optional,

**Pull request merged**
