### PR TITLE
SDK-186 Isolating docker image which can be deployed to dockerhub

### PR DESCRIPTION
**Pull request by cintiadr**
So, the magic I did here is splitting the Docker image (the binary/artefact) from the docker compose (database, environment variables, and so on). 

If I go to reference application, for example:
```
$ mvn org.openmrs.maven.plugins:openmrs-sdk-maven-plugin:3.5.1-SNAPSHOT:build-distro -B -Ddir=something
$ cd something/referenceapplication-docker-image
$ docker build -t cintiadr/openmrs-refapp-demo:latest
$ docker push cintiadr/openmrs-refapp-demo:latest
```
 

...and we have https://hub.docker.com/r/cintiadr/openmrs-refapp-demo/tags/

Now, I can deploy changing only docker-compose, deploying to several different environments using the same docker image, as you can check in https://github.com/cintiadr/docker-openmrs

(OK, I _think_ everything appears to be working as before, but I might not have tested every use case...)

### CODE REVIEW

**Comment by dkayiwa** [comment]
@rkorytkowski @AdamGrzybkowski @PawelGutkowski @tmarzeion do you wanna merge this? :)

**Comment by rkorytkowski** [comment]
@dkayiwa, it looks good overall. I'm deferring with merging until I have some time to test it manually.

**Comment by cintiadr** [comment]
Yes, please, I'd love to have others testing it too!

**Comment by dkayiwa** [comment]
@rkorytkowski @AdamGrzybkowski @PawelGutkowski @tmarzeion this pull request now has merge conflicts. Could it be because you already put in the necessary changes?

Am just going through pull requests that have been open for long. :)

**Comment by cintiadr** [comment]
No, it's not merged. I will fix the conflicts tomorrow.

**Comment by rkorytkowski** [comment]
@cintiadr, awesome! I'll make sure your work get tested during current SDK sprint... We just need to create an issue in the SDK project describing what you did...

**Comment by cintiadr** [comment]
Issue https://issues.openmrs.org/browse/SDK-186. 

I believe I merged the only relevant change (the timeout for mysql). I checked the rest of the commits, they seem pretty unrelated.

**Pull request merged**
