### PR TITLE
SDK-289:Set OWA artifactId to return SystemAdministration

### PR DESCRIPTION
**Pull request by sherrif10**
https://issues.openmrs.org/browse/SDK-289  cc @dkayiwa  @ibacher  .

### CODE REVIEW

**Comment by HerbertYiga** [comment]
thanks @sherrif10  i see some breaking builds for this

**Comment by sherrif10** [comment]
Hello @HerbertYiga , Am having issues with sdk module, there are integration test failures which we are looking into for the moment

**Comment by ibacher** [comment]
@sherrif10 Thanks for the attempted PR. I made a mistake in where the change should be made, so I added an even uglier hack to address this in f4987498.

**Comment by sherrif10** [comment]
Ok sure. Thanks for letting me know. We can catch up on the pr

**Pull request closed without merging**
