### PR TITLE
SDK-307: Update source and target Java version to 1.8.

### PR DESCRIPTION
**Pull request by wikumChamith**
Update the source and target Java version to 1.8.

Jira ticket: https://issues.openmrs.org/browse/SDK-307

### CODE REVIEW

**Comment by dkayiwa** [comment]
@wikumChamith i thought Java 8 was for the master branch. Not so?

**Comment by wikumChamith** [comment]
> @wikumChamith i thought Java 8 was for the master branch. Not so?

Sorry, I thought this branch was created for Java 8 changes. I edited the PR to commit into master.

**Comment by dkayiwa** [comment]
@wikumChamith didn't we also agree to bump the major version?

**Comment by wikumChamith** [comment]
> @wikumChamith didn't we also agree to bump the major version?

@dkayiwa do you mean changing the version of maven plugin

**Comment by dkayiwa** [comment]
I mean the maven pom version.

**Comment by wikumChamith** [comment]
> I mean the maven pom version.

I was gonna do it after finishing Java 8 tickets.

**Comment by dkayiwa** [comment]
The problem is that we have both the master branch and the other branch producing the exact same version of the snapshot artifacts.

**Comment by wikumChamith** [comment]
> The problem is that we have both the master branch and the other branch producing the exact same version of the snapshot artifacts.

Are you talking about the maven version ?? or the version of the SDK?? Didn't we bump the version of SDK to 4.7.0-SNAPSHOT??

**Comment by dkayiwa** [comment]
Which version of the sdk snapshot is the master branch producing? And which snapshot version is the other pre 1.8 branch producing?

**Comment by wikumChamith** [comment]
> Which version of the sdk snapshot is the master branch producing? And which snapshot version is the other pre 1.8 branch producing?

Both of them are using 4.7 SNAPSHOT, should I  bump this to 4.8 SNAPSHOT??

**Comment by dkayiwa** [comment]
5.0.0-SNAPSHOT

**Comment by wikumChamith** [comment]
> 5.0.0-SNAPSHOT

I created this PR: https://github.com/openmrs/openmrs-sdk/pull/229

**Pull request merged**
