### PR TITLE
Use proxy for bintray downloads

### PR DESCRIPTION
**Pull request by lilian-arnaud**
if you access internet through a proxy, the download of binary files via HTTP fails.
This change allows the maven-plugin of the SDK to use the proxy information stored in the global settings to connect to internet and to download files.

### CODE REVIEW

**Comment by dkayiwa** [comment]
Thanks @lilian-arnaud for the contribution!
Do you mind creating a ticket for this as advised at? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

https://wiki.openmrs.org/display/docs/Tickets

**Comment by lilian-arnaud** [comment]
Hi,

I’m in process to create it :). 
Expect it in the coming hour!

Kind Regards,
Lilian

**Comment by lilian-arnaud** [comment]
the ticket is https://issues.openmrs.org/browse/SDK-236

**Comment by dkayiwa** [comment]
@rkorytkowski could you be having any comments on this? 😊

**Comment by rkorytkowski** [comment]
Looks good to me! Thanks @lilian-arnaud !

**Comment by lilian-arnaud** [comment]
you are welcome :)

**Pull request merged**
