### PR TITLE
Using try-with-resources is more concise and safer way of managing resources

### PR DESCRIPTION
**Pull request by Engineer-mostafa**
[1] converting normal try to try-with-resources
[2] add 1 more exception for file if not finding the path

### CODE REVIEW

**Comment by Engineer-mostafa** [comment]
@dkayiwa

**Comment by dkayiwa** [comment]
Thanks @Engineer-mostafa for contributing! Did you create a ticket for this?

**Comment by Engineer-mostafa** [comment]
not yet, can you refer a doc for this and i will do immediately @dkayiwa

**Comment by dkayiwa** [comment]
Did you also get a chance to look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Pull request closed without merging**
