### PR TITLE
SDK-298: SDK Setup should support non-interactive usage for all options

### PR DESCRIPTION
**Pull request by wikumChamith**
## Description of what I changed

Generating the documentation using the Maven help plugin

## Issue I worked on

see https://issues.openmrs.org/browse/SDK-298

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean install` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute the above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

### CODE REVIEW

**Comment by ibacher** [comment]
@wikumChamith What's the status of this?

**Comment by wikumChamith** [comment]
@ibacher I was waiting for a review on this PR. Do you know if the way I implemented this is correct?

**Comment by wikumChamith** [comment]
@dkayiwa, @ibacher can you take a look at this PR?

**Review by ibacher — APPROVED** [review]

**Comment by ibacher** [comment]
Excellent. Let's get this in. We can work on the docs later.

**Pull request merged**
