### PR TITLE
SDK-235 Enable artifact names to contain dashes

### PR DESCRIPTION
**Pull request by ssmusoke**
https://issues.openmrs.org/browse/SDK-235 with original discussion https://talk.openmrs.org/t/custom-module-development-importing-all-dependencies-from-existing-module-and-extending-openmrs-distro-properties-file/18588/15

### CODE REVIEW

**Comment by dkayiwa** [comment]
Including a direct link to the ticket as tipped at https://wiki.openmrs.org/display/docs/Pull+Request+Tips simplifies work for the reviewer.
Secondly, including a link to the talk post, on the JIRA ticket, gives more context to the problem being solved.

**Comment by dkayiwa** [comment]
Did you try out your ticket link? 😊

**Comment by ssmusoke** [comment]
@dkayiwa yes I did - all links work fine

**Comment by dkayiwa** [comment]
Did you see what it opens up?

**Comment by ssmusoke** [comment]
@dkayiwa seen what you were referring to and updated

**Pull request merged**
